### ISSUE TITLE
QUESTION: Which raspberry pi you're using? 

### ISSUE THREAD

**Issue by MrPineMan** [skalavala/Multi-Room-Audio-Centralized-Audio-for-Home#1]
In the system overview drawing you used many raspberry's. Are all of these raspberry 2 or 3's ?

Did you ever used a Pi Zero with Bluetooth? instant of AUX to connect with pulse audio ? And did it worked out ?

**Comment by skalavala** [comment]
I never paid attention to the issue section of the repository... sorry for the delayed response. I use Raspberry Pi 3s at home. Bluetooth is a pain to set it up, and distance is a problem for me in my house. I have these devices in Garage, Basement, Ground floor and Upstairs in the house (in all corners), and Bluetooth just wouldn't work.

Pi Zeros doesn't have audio jack, and besides the RPIs I have in each room does multiple things, they are being used heavily all the time.
