### ISSUE TITLE
Addon

### ISSUE THREAD

**Issue by MrPineMan** [skalavala/Multi-Room-Audio-Centralized-Audio-for-Home#2]
libavahi-client3 is required in sketch before sudo dpkg -i snapclient_0.12.0_armhf.deb

sudo apt install libavahi-client3 
make it work, good work anyways!

**Comment by skalavala** [comment]
I never had to install `libavahi-client3`. on a raspberry pi  for `snapclient` to work. You can always run the command, and it wouldn't hurt.
